### ISSUE TITLE
Unable to build on MacOS Sequoia 15.2

### ISSUE THREAD

**Issue by alexandredoyen29** [Cryptiiiic/x8A4#6]
Hi !

Thank you for your work.

I have the following issue when I try to build x8A4 on my M4 Mac :
```
alexandredoyen@mac-mini ~/Documents/Git/x8A4> /Applications/CMake.app/Contents/bin/cmake .
-- The C compiler identification is AppleClang 16.0.0.16000026
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done (0.2s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/alexandredoyen/Documents/Git/x8A4
alexandredoyen@mac-mini ~/Documents/Git/x8A4> make
[  7%] Building C object CMakeFiles/x8A4.dir/x8A4.c.o
In file included from /Users/alexandredoyen/Documents/Git/x8A4/x8A4.c:19:
In file included from /Users/alexandredoyen/Documents/Git/x8A4/include/x8A4/x8A4.h:21:
In file included from /Users/alexandredoyen/Documents/Git/x8A4/include/x8A4/Kernel/kpf.h:20:
/Users/alexandredoyen/Documents/Git/x8A4/include/XPF/xpf.h:3:10: error: non-portable path to file '<choma/FAT.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
    3 | #include <choma/Fat.h>
      |          ^~~~~~~~~~~~~
      |          <choma/FAT.h>
In file included from /Users/alexandredoyen/Documents/Git/x8A4/x8A4.c:19:
In file included from /Users/alexandredoyen/Documents/Git/x8A4/include/x8A4/x8A4.h:21:
In file included from /Users/alexandredoyen/Documents/Git/x8A4/include/x8A4/Kernel/kpf.h:20:
In file included from /Users/alexandredoyen/Documents/Git/x8A4/include/XPF/xpf.h:5:
In file included from /Users/alexandredoyen/Documents/Git/x8A4/include/choma/PatchFinder.h:5:
/Users/alexandredoyen/Documents/Git/x8A4/include/choma/MachO.h:8:10: error: non-portable path to file '"FAT.h"'; specified path differs in case from file name on disk [-Werror,-Wnonportable-include-path]
    8 | #include "Fat.h"
      |          ^~~~~~~
      |          "FAT.h"
2 errors generated.
make[2]: *** [CMakeFiles/x8A4.dir/x8A4.c.o] Error 1
make[1]: *** [CMakeFiles/x8A4.dir/all] Error 2
make: *** [all] Error 2
```

I think it is because this soft is designed to be built on linux. So, could you tell what are dependencies ?

Best regards

**Comment by alexandredoyen29** [comment]
In addition, I forgot to tell that I have the IOKernelRW kext installed.

**Comment by Cryptiiiic** [comment]
@alexandredoyen29 try this patch:
<img width="443" alt="image" src="https://github.com/user-attachments/assets/034fca97-5154-4d9f-9b37-36659f0dbb2c" />
```CMAKE
target_include_directories(x8A4 PRIVATE
        "${CMAKE_SOURCE_DIR}/Include/choma"
        "${CMAKE_SOURCE_DIR}/Include")

```

**Comment by alexandredoyen29** [comment]
> @alexandredoyen29 try this patch:
> <img width="443" alt="image" src="https://github.com/user-attachments/assets/034fca97-5154-4d9f-9b37-36659f0dbb2c" />
> ```CMAKE
> target_include_directories(x8A4 PRIVATE
>         "${CMAKE_SOURCE_DIR}/Include/choma"
>         "${CMAKE_SOURCE_DIR}/Include")
> 
> ```

OK, I will try this this evening!

**Comment by alexandredoyen29** [comment]
OK, I tried your patch, and moved `Include/choma/FAT.h` to `Include/choma/Fat.h`.

Now, I have this error. I think one library is missing...

```
alexandredoyen@mac-mini ~/Documents/Git/x8A4> make clean && make
[  7%] Building C object CMakeFiles/x8A4.dir/x8A4.c.o
[ 15%] Building C object CMakeFiles/x8A4.dir/Logger/logger.c.o
[ 23%] Building C object CMakeFiles/x8A4.dir/Kernel/slide.c.o
[ 30%] Building C object CMakeFiles/x8A4.dir/Services/services.c.o
[ 38%] Building C object CMakeFiles/x8A4.dir/Registry/registry.c.o
[ 46%] Building C object CMakeFiles/x8A4.dir/Kernel/kernel.c.o
[ 53%] Building C object CMakeFiles/x8A4.dir/Kernel/offsets.c.o
[ 61%] Building C object CMakeFiles/x8A4.dir/Kernel/kpf.c.o
[ 69%] Building C object CMakeFiles/x8A4.dir/Kernel/osobject.c.o
[ 76%] Building C object CMakeFiles/x8A4.dir/Kernel/nvram.c.o
[ 84%] Linking C shared library libx8A4.dylib
Signing libx8A4.1.dylib...
make[2]: ldid: No such file or directory
make[2]: *** [libx8A4.1.dylib] Error 1
make[2]: *** Deleting file `libx8A4.1.dylib'
make[1]: *** [CMakeFiles/x8A4.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by alexandredoyen29** [comment]
Ok, I just had to install Homebrew and install the ldid package !
